[versions]
capsule = "0.0.1-SNAPSHOT"
slider = "0.0.18"
kotlin = "2.4.10"
junit-platform-launcher = "1.10.2"
junit-platform = "1.14.3"
playwright = "1.52.0"
kover = "0.9.8"
cucumber = "7.34.3"
jackson = "2.18.3"
codebase = "0.0.10"
koog = "1.0.0"
workspace-bom = "0.0.27"
i18n-contracts = "0.0.2"
codebase-contracts = "0.0.2"

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8" }
slider = { group = "education.cccp", name = "slider-plugin", version.ref = "slider" }
playwright = { group = "com.microsoft.playwright", name = "playwright", version.ref = "playwright" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumber" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
codebase-plugin = { module = "education.cccp:codebase-plugin", version.ref = "codebase" }
langchain4j = { module = "dev.langchain4j:langchain4j" }
langchain4j-ollama = { module = "dev.langchain4j:langchain4j-ollama" }
i18n-contracts = { module = "education.cccp:i18n-contracts", version.ref = "i18n-contracts" }
codebase-contracts = { module = "education.cccp:codebase-contracts", version.ref = "codebase-contracts" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
capsule = { id = "education.cccp.capsule", version.ref = "capsule" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
codebase = { id = "education.cccp.codebase", version.ref = "codebase" }

[bundles]
cucumber = [
    "cucumber-java",
    "cucumber-junit-platform-engine",
    "cucumber-picocontainer",
    "junit-platform-suite",
]
